### PR TITLE
Adding new WCAG document for Satellite 6.4

### PR DESCRIPTION
**Pull request by bhirsch70**
Adding new WCAG document for Satellite 6.4 to be included as a product document in the yet-to-be-created section for Red Hat Satellite

### CODE REVIEW

**Comment by shawndwells** [comment]
Didn't catch this earlier (sorry!) - just noticed the docs have specific version numbers (``Sat 6.4``). Can these be ``6.x`` or is specific minor releases needed?

**Comment by bhirsch70** [comment]
Good point.  The truth is, I only tested it on 6.4, but I think we can
probably get away with putting 6.x in there.  I'll upload a new version.

BILL HIRSCH

PRINCIPAL SOLUTIONS ARCHITECT, RHCE, RHCA

Red Hat

<https://www.redhat.com/>

bhirsch@redhat.com    M: 724.719.7106
<https://red.ht/sig>
TRIED. TESTED. TRUSTED. <https://redhat.com/trusted>
@redhat <https://twitter.com/RedHat>   Red Hat
<https://www.linkedin.com/company/red-hat>   Red Hat
<https://www.facebook.com/RedHatInc>

**Comment by bhirsch70** [comment]
New version is uploaded.  Ready for merge.

**Comment by redhatrises** [comment]
ack.

**Comment by shawndwells** [comment]
@redhatrises oddly, this didn't kickoff the openshift pipeline

https://console.pro-us-east-1.openshift.com/console/project/ato-pathways/browse/builds

**Pull request merged**
